# Generated by Django 3.1.4 on 2021-05-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0003_auto_20210512_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='owner',
            field=models.ForeignKey(db_column='owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
