# Generated by Django 3.1.4 on 2021-05-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20210512_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='owner',
        ),
    ]
